[package]
name = "light-contact"
version = "0.1.0"
edition = "2021"

[dependencies]
#bevy = { version = "0.7" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }

#bevy = { git = "https://github.com/cart/bevy", branch = "better-materials" }
#bevy-ui-navigation = { path = "../ui-navigation" }
#bevy_asset_loader = "0.11.0"
